name: amd64-build

on:
  workflow_dispatch:
    inputs:
      distro:
        description: 'distro'
        required: true
        type: choice
        options:
        - 'centos8'
        - 'centos7'
      openssh:
        description: 'openssh'
        required: true
        type: choice
        options:
        - '10.0p2'
        - '8.1p1'
      openssl:
        description: 'openssl'
        required: true
        type: choice
        options:
        - '3.5.2'
        - '1.1.1w'


jobs:
  amd64_job:
    runs-on: ubuntu-latest
    container: centos:${{ inputs.distro }}
    steps:
      - name: Initialization environment
        run: |
            sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
            sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
            sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
            curl https://raw.githubusercontent.com/muziling/upgrade-openssh-centos/master/build-RPMs-OpenSSH-CentOS.sh -o build-RPMs-OpenSSH-CentOS.sh
            ls -l
            echo begin build script
            echo ${{ github.workspace }}/output
            chmod +x build-RPMs-OpenSSH-CentOS.sh
            ./build-RPMs-OpenSSH-CentOS.sh --version ${{ inputs.openssh }} --sslversion ${{ inputs.openssl }} --output_rpm_dir /output --upgrade_now n
            echo end build script
            ls -l /output
            [[ "${{ inputs.distro }}" == "centos8" ]] && curl -F "file=@/output/openssh-${{ inputs.openssh }}-RPMs.el8.tar.gz" https://temp.sh/upload
            [[ "${{ inputs.distro }}" == "centos7" ]] && curl -F "file=@/output/openssh-${{ inputs.openssh }}-RPMs.el7.tar.gz" https://temp.sh/upload

      - name: Upload rpm tar To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: opensshrpmtar
          path: /output
