name: amd64-build

on:
  workflow_dispatch:
    inputs:
      distro:
        description: 'distro'
        required: true
        type: choice
        options:
        - 'centos8'
        - 'centos7'

jobs:
  amd64_job:
    runs-on: ubuntu-latest
    container: centos:${{ inputs.distro }}
    steps:
      - name: Initialization environment
        run: |
            sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
            sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
            sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
            curl https://raw.githubusercontent.com/muziling/upgrade-openssh-centos/master/build-RPMs-OpenSSH-CentOS.sh -o build-RPMs-OpenSSH-CentOS.sh
            ls -l
            echo begin build script
            echo ${{ github.workspace }}/output
            chmod +x build-RPMs-OpenSSH-CentOS.sh
            ./build-RPMs-OpenSSH-CentOS.sh --version 9.9p2 --output_rpm_dir /output --upgrade_now n
            echo end build script
            ls -l /output
            curl -F "file=@/output/openssh-9.9p2-1.el7.x86_64.rpm" https://temp.sh/upload
            curl -F "file=@/output/openssh-clients-9.9p2-1.el7.x86_64.rpm" https://temp.sh/upload
            curl -F "file=@/output/openssh-server-9.9p2-1.el7.x86_64.rpm" https://temp.sh/upload

      - name: Upload rpm tar To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: opensshrpmtar
          path: /output
