name: arm

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'arch'
        required: true
        type: choice
        options:
        - 'aarch64'
      distro:
        description: 'distro'
        required: true
        type: choice
        options:
        - 'centos8'
        - 'centos7'
      openssh:
        description: 'openssh'
        required: true
        type: choice
        options:
        - '10.0p2'
        - '8.1p1'
      openssl:
        description: 'openssl'
        required: true
        type: choice
        options:
        - '10.0p2'
        - '1.1.1w'

jobs:
  armv8_job:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: muziling/run-on-arch-action@master
        name: Run commands
        id: runcmd
        with:
          arch: ${{ inputs.arch }}
          distro: ${{ inputs.distro }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            mkdir /rpmoutput
            curl https://raw.githubusercontent.com/muziling/upgrade-openssh-centos/master/build-RPMs-OpenSSH-CentOS.sh -o build-RPMs-OpenSSH-CentOS.sh
            ls -l
            echo begin build script
            echo ${{ github.workspace }}/output
            chmod +x build-RPMs-OpenSSH-CentOS.sh
            ./build-RPMs-OpenSSH-CentOS.sh --version ${{ inputs.openssh }} --sslversion ${{ inputs.openssl }} --output_rpm_dir ${{ github.workspace }}/output --upgrade_now n
            echo end build script

      - name: Upload rpm tar To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: opensshrpmtar
          path: ${{ github.workspace }}/output
