name: openssh

on:
  workflow_dispatch:

jobs:
  armv8_job:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: muziling/run-on-arch-action@master
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: centos8

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            mkdir /rpmoutput
            wget https://github.com/muziling/upgrade-openssh-centos/raw/master/build-RPMs-OpenSSH-CentOS.sh
            bash build-RPMs-OpenSSH-CentOS.sh --version 9.8p1 --output_rpm_dir /rpmoutput

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: opensshrpm
          path: /rpmoutput
