name: android my-tv build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: muziling/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: centos8

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            mkdir /rpmoutput
            bash build-RPMs-OpenSSH-CentOS.sh --version 9.8p1 --install_only=justbuild --output_rpm_dir=/rpmoutput

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: opensshrpm
          path: rpmoutput
